[package]
name = "snowbridge-outbound-queue-runtime-api-v2"
description = "Snowbridge Outbound Queue Runtime API V2"
version = "0.2.0"
authors = ["Snowfork <contact@snowfork.com>"]
edition.workspace = true
repository.workspace = true
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive"], workspace = true }
sp-std = { workspace = true }
sp-api = { workspace = true }
frame-support = { workspace = true }
snowbridge-core = { workspace = true }
snowbridge-merkle-tree = { workspace = true }
xcm = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"scale-info/std",
	"snowbridge-core/std",
	"snowbridge-merkle-tree/std",
	"sp-api/std",
	"sp-std/std",
	"xcm/std",
]
