// Copyright (C) Parity Technologies (UK) Ltd.
// This file is part of Polkadot.

// Polkadot is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// Polkadot is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with Polkadot.  If not, see <http://www.gnu.org/licenses/>.

//! # Speculative Outbox Pallet
//!
//! Sender-side pallet for the inclusion-based speculative messaging PoC.
//!
//! Maintains per-destination MMRs accumulating all outbound messages using a
//! peaks-only representation (O(log n) storage), stores payload bytes on-chain,
//! and exposes runtime APIs for providers to query `MessageBatch`es.
//!
//! The MMR uses `mmr_lib` with the domain-tagged `blake2_256` `SpecMerge` from
//! `cumulus-primitives-spec-messaging`; leaves are `OutgoingMessage::hash_leaf`
//! values and a destination's `subtree_root` is its peaks bagged with
//! `root_from_peaks`. The `provides` commitment is the flat `CommitmentSet` of
//! `(destination, subtree_root)` entries — there is no top-level Merkle tree.
//!
//! Implements `XcmpMessageSource` by wrapping the inner source (typically
//! `XcmpQueue`), recording outbound messages in the speculative MMR while
//! still forwarding them for standard HRMP delivery.

#![cfg_attr(not(feature = "std"), no_std)]

extern crate alloc;
use alloc::{collections::BTreeSet, vec, vec::Vec};

use codec::{Decode, DecodeWithMemTracking, Encode};
use scale_info::TypeInfo;
use sp_core::H256;
use sp_runtime::BoundedVec;

use frame_support::pallet_prelude::*;
use frame_system::{
	ensure_none,
	pallet_prelude::{BlockNumberFor, OriginFor},
};
use sp_inherents::InherentIdentifier;

use cumulus_pallet_parachain_system::{RelayChainStateProof, RelaychainStateProvider};
use cumulus_primitives_core::{relay_chain, ParaId, XcmpMessageSource};
use cumulus_primitives_spec_messaging::{
	mmr::{root_from_peaks, Mmr, MmrAccumulator, SpecMerge},
	LateBlockProof, MaxSpeculativeMessageLen, OutgoingMessage, SpecHasher, SubtreeExtension,
};
use polkadot_primitives::v9::{ProvidesCommitment, MAX_DESTINATIONS_PER_BLOCK};

use mmr_lib::{leaf_index_to_pos, MMRStoreReadOps, MMRStoreWriteOps, MMR};

/// Maximum number of consumed payloads pruned in a single [`Pallet::apply_ack`] call. Bounds the
/// weight of an ack; any remaining backlog drains in `on_idle` or on the next ack (follow-up to
/// #12350, see `docs/speculative-messaging-impl-design.md`).
const MAX_PRUNE_PER_CALL: u64 = 100;

/// Maximum total payloads pruned across all destinations in a single `on_idle` sweep.
const MAX_PRUNE_PER_IDLE: u64 = 500;

/// Maximum destinations visited in a single `on_idle` prune sweep.
const MAX_DESTS_PER_IDLE: usize = 50;

/// Maximum number of receiver acks processed in a single [`Pallet::note_consumed`] call. Bounds the
/// extrinsic's weight and proof size.
const MAX_ACKS_PER_CALL: usize = 64;

/// Inherent identifier for the collator-injected consumed-ack inherent. Mirrored by
/// [`client::INHERENT_IDENTIFIER`].
pub const INHERENT_IDENTIFIER: InherentIdentifier = *b"specackn";

/// Collator-supplied relay proof of receiver consumption, carried as an optional inherent and
/// applied by [`Pallet::note_consumed`]. `proof` is a relay state proof against the current relay
/// parent committing the `ParaInclusion::LatestRequires(self, receiver)` entries for `receivers`.
#[derive(Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, Eq, Debug, TypeInfo)]
pub struct ConsumedAck {
	/// Relay state proof containing the `LatestRequires` entries for `receivers`.
	pub proof: sp_trie::StorageProof,
	/// Receivers whose acks are proven and should be applied.
	pub receivers: Vec<ParaId>,
}

/// MMR state for a single destination's subtree (peaks-only representation).
#[derive(Clone, Encode, Decode, TypeInfo, Default)]
pub struct MMRState {
	/// Number of leaves inserted so far (the MMR `size`).
	pub leaf_count: u64,
	/// MMR peaks — O(log n) hashes sufficient to reconstruct the subtree root.
	pub peaks: Vec<H256>,
	/// Total `mmr_lib` node count (positions), tracked so the persistent node store
	/// ([`OutgoingMmrNodes`]) can be reopened as `MMR::new(mmr_size, store)` for proof generation.
	pub mmr_size: u64,
}

/// Persistent `mmr_lib` store for a destination's outbound MMR nodes, backed by
/// [`OutgoingMmrNodes`]. Lets proofs be generated by reading stored nodes (O(log n)) instead of
/// replaying every payload, so consumed payloads can be pruned without breaking proof generation
/// (follow-up to #12350).
struct OutboxStore<T>(ParaId, core::marker::PhantomData<T>);

impl<T> OutboxStore<T> {
	fn new(dest: ParaId) -> Self {
		Self(dest, core::marker::PhantomData)
	}
}

impl<T: Config> MMRStoreReadOps<H256> for OutboxStore<T> {
	fn get_elem(&self, pos: u64) -> mmr_lib::Result<Option<H256>> {
		Ok(OutgoingMmrNodes::<T>::get(self.0, pos))
	}
}

impl<T: Config> MMRStoreWriteOps<H256> for OutboxStore<T> {
	fn append(&mut self, pos: u64, elems: Vec<H256>) -> mmr_lib::Result<()> {
		for (i, elem) in elems.into_iter().enumerate() {
			OutgoingMmrNodes::<T>::insert(self.0, pos + i as u64, elem);
		}
		Ok(())
	}
}

pub use pallet::*;

#[cfg(feature = "std")]
pub mod client;

#[frame_support::pallet]
pub mod pallet {
	use super::*;

	#[pallet::pallet]
	#[pallet::without_storage_info]
	pub struct Pallet<T>(_);

	#[pallet::config]
	pub trait Config: frame_system::Config<RuntimeEvent: From<Event<Self>>> {
		/// The inner XCMP message source (typically `XcmpQueue`).
		type InnerXcmpMessageSource: XcmpMessageSource;
		/// This parachain's own id, bound into each message's `hash_leaf` preimage.
		type SelfParaId: Get<ParaId>;
		/// Maximum number of unconsumed (stored-but-not-yet-pruned) speculative payloads to retain
		/// per destination. When a destination is at this cap, further messages to it fall back to
		/// plain HRMP delivery instead of being recorded speculatively. This bounds worst-case
		/// storage for a receiver that never acknowledges (follow-up to #12350).
		type MaxBacklogPerDestination: Get<u64>;
		/// Provides the current relay-parent state root and number — the trust anchor against which
		/// `note_consumed` proofs are verified. Typically
		/// `cumulus_pallet_parachain_system::RelaychainDataProvider`.
		type RelayState: RelaychainStateProvider;
		/// Finality depth `K`: an ack enacted on the relay is only acted upon once it is at least
		/// this many blocks behind the relay parent, so a dispute-driven revert can never make the
		/// sender prune data a receiver still needs. Set to (at least) the relay's dispute period.
		type AckFinalityDepth: Get<relay_chain::BlockNumber>;
	}

	#[pallet::event]
	#[pallet::generate_deposit(pub(super) fn deposit_event)]
	pub enum Event<T: Config> {
		MessagesRecorded {
			destination: ParaId,
			count: u32,
		},
		/// A destination's consumed watermark advanced after an acknowledged `requires` root,
		/// allowing payloads below `position` to be pruned.
		ConsumedWatermarkAdvanced {
			destination: ParaId,
			position: u64,
		},
		/// A destination hit its unconsumed-backlog cap; messages to it this block fell back to
		/// plain HRMP delivery instead of being recorded speculatively.
		BacklogCapReached {
			destination: ParaId,
		},
	}

	#[pallet::error]
	pub enum Error<T> {
		/// The supplied relay state proof did not verify against the relay-parent state root, or a
		/// `LatestRequires` entry failed to decode.
		InvalidRelayProof,
		/// More receivers were supplied than [`MAX_ACKS_PER_CALL`].
		TooManyAcks,
	}

	/// Per-destination MMR state (leaf count + peaks).
	#[pallet::storage]
	pub type OutgoingMMRState<T: Config> =
		StorageMap<_, Twox64Concat, ParaId, MMRState, ValueQuery>;

	/// Payload bytes for outgoing messages.
	#[pallet::storage]
	pub type OutgoingMessages<T: Config> =
		StorageDoubleMap<_, Twox64Concat, ParaId, Twox64Concat, u64, Vec<u8>>;

	/// Persistent MMR node store per destination (`mmr_lib` node position -> hash). Populated as
	/// leaves are appended in [`Pallet::record_outbound_messages`] and read by the proof generators
	/// so they need not replay payloads — which is what makes payload pruning safe.
	#[pallet::storage]
	pub type OutgoingMmrNodes<T: Config> =
		StorageDoubleMap<_, Twox64Concat, ParaId, Twox64Concat, u64, H256, OptionQuery>;

	/// Destinations whose subtree root changed since the last rotation. Filled by
	/// [`Pallet::record_outbound_messages`] as messages are taken, then promoted into
	/// [`ProvidesThisBlock`] at `on_initialize` of the following block. This is the
	/// accumulator side of the delta-`provides` rotation; it is never read directly by
	/// `compute_provides`.
	#[pallet::storage]
	pub type PendingProvides<T: Config> = StorageValue<
		_,
		frame_support::BoundedBTreeSet<ParaId, sp_core::ConstU32<MAX_DESTINATIONS_PER_BLOCK>>,
		ValueQuery,
	>;

	/// Frozen snapshot of the destinations to commit in *this* block's `provides`. Rotated
	/// in from [`PendingProvides`] at `on_initialize` so it is stable for the whole block
	/// (both the on-chain `speculative_extension` read and the off-chain runtime API see the
	/// same set), while `record_outbound_messages` fills a fresh accumulator for next block.
	#[pallet::storage]
	pub type ProvidesThisBlock<T: Config> = StorageValue<
		_,
		frame_support::BoundedBTreeSet<ParaId, sp_core::ConstU32<MAX_DESTINATIONS_PER_BLOCK>>,
		ValueQuery,
	>;

	/// Durable index from a committed (end-of-block) subtree root to its `(leaf_count, block)`, per
	/// destination. `apply_ack` maps a receiver's acknowledged `requires` root to a consumed
	/// position through this map; `block_number_for_subtree_root` reads the block tag. Entries are
	/// pruned once fully consumed (below the watermark), so it is not capped to a fixed block window
	/// — this is what lets slow / on-demand receivers acknowledge an arbitrarily old root, and it
	/// subsumes the former `HistoricalSubtreeState` (follow-up to #12350).
	#[pallet::storage]
	pub type CommittedRootPosition<T: Config> = StorageDoubleMap<
		_,
		Twox64Concat,
		ParaId,
		Identity,
		H256,
		(u64, BlockNumberFor<T>),
		OptionQuery,
	>;

	/// Per-destination consumed watermark: the leaf count the receiver has provably consumed up to
	/// (monotonic). Payloads below it are eligible for pruning. Advanced by [`Pallet::apply_ack`].
	#[pallet::storage]
	pub type ConsumedWatermark<T: Config> = StorageMap<_, Twox64Concat, ParaId, u64, ValueQuery>;

	/// Per-destination prune cursor: payloads strictly below this position have been deleted.
	/// Chases [`ConsumedWatermark`] in capped steps so a large jump cannot make a single call
	/// unbounded.
	#[pallet::storage]
	pub type PrunedUpTo<T: Config> = StorageMap<_, Twox64Concat, ParaId, u64, ValueQuery>;

	/// Per-destination node-prune cursor: the leaf count up to whose completed left subtrees the
	/// persistent MMR node store has been pruned. Only the prefix's peaks (the witness frontier) are
	/// kept below this; everything strictly inside fully-consumed subtrees is deleted. Chases
	/// [`ConsumedWatermark`] in capped steps.
	#[pallet::storage]
	pub type NodePrunedUpTo<T: Config> = StorageMap<_, Twox64Concat, ParaId, u64, ValueQuery>;

	#[pallet::hooks]
	impl<T: Config> Hooks<BlockNumberFor<T>> for Pallet<T> {
		fn on_initialize(_n: BlockNumberFor<T>) -> Weight {
			// Promote the destinations recorded during the previous block's
			// `take_outbound_messages` into this block's provides snapshot, and reset the
			// accumulator. `parachain-system` reads `compute_provides` (in its `on_finalize`)
			// *before* it calls `take_outbound_messages`, so the delta we publish in block N is
			// exactly what was recorded in block N-1 — the same one-block lag the cumulative
			// implementation already had.
			ProvidesThisBlock::<T>::put(PendingProvides::<T>::take());
			T::DbWeight::get().reads_writes(1, 2)
		}

		fn on_finalize(n: BlockNumberFor<T>) {
			// Record each active destination's current (end-of-block) subtree root in the durable
			// root index, tagged with this block. Used by `apply_ack` (root -> leaf count) and
			// `block_number_for_subtree_root` (root -> block); pruned by the consumed watermark.
			for (dest, state) in OutgoingMMRState::<T>::iter() {
				if state.leaf_count == 0 {
					continue;
				}
				let root = root_from_peaks::<SpecHasher>(&state.peaks);
				CommittedRootPosition::<T>::insert(dest, root, (state.leaf_count, n));
			}
		}

		fn on_idle(_n: BlockNumberFor<T>, remaining: Weight) -> Weight {
			// Best-effort: continue draining acknowledged-but-not-yet-deleted payloads for
			// destinations whose prune cursor lags their watermark. Bounded by a fixed deletion
			// budget and destination count so the sweep stays within block weight.
			let unit = T::DbWeight::get().reads_writes(1, 1);
			if remaining.any_lt(unit) {
				return Weight::zero();
			}

			let mut budget = MAX_PRUNE_PER_IDLE;
			let dests: Vec<ParaId> = PrunedUpTo::<T>::iter()
				.filter(|(dest, pruned)| *pruned < ConsumedWatermark::<T>::get(dest))
				.map(|(dest, _)| dest)
				.take(MAX_DESTS_PER_IDLE)
				.collect();

			let mut deleted = 0u64;
			for dest in dests {
				if budget == 0 {
					break;
				}
				let n = Self::prune_consumed(dest, budget);
				budget = budget.saturating_sub(n);
				deleted = deleted.saturating_add(n);
			}

			// Also reclaim persistent MMR nodes inside fully-consumed subtrees, keeping the witness
			// frontier so proofs for un-consumed leaves still verify.
			let node_dests: Vec<ParaId> = ConsumedWatermark::<T>::iter()
				.filter(|(dest, watermark)| NodePrunedUpTo::<T>::get(dest) < *watermark)
				.map(|(dest, _)| dest)
				.take(MAX_DESTS_PER_IDLE)
				.collect();
			for dest in node_dests {
				let removed = Self::prune_nodes(dest, MAX_PRUNE_PER_CALL);
				deleted = deleted.saturating_add(removed);
			}

			unit.saturating_mul(deleted.saturating_add(1))
		}
	}

	#[pallet::call]
	impl<T: Config> Pallet<T> {
		/// Advance consumed watermarks from relay-verified `requires` acks and prune acknowledged
		/// payloads. Permissionless: it only advances strictly-monotonic watermarks using data
		/// proven against the relay-parent state root, gated `K`-deep for finality, so a malicious
		/// caller can at worst under-report (prune less) — never strand a receiver or over-prune.
		///
		/// `proof` is a relay state proof (against the current relay parent) that must contain the
		/// `ParaInclusion::LatestRequires(self, receiver)` entries for each `receiver` in
		/// `receivers`. The collator builds it from the `latest_requires_for_source` runtime API.
		#[pallet::call_index(0)]
		#[pallet::weight(T::DbWeight::get().reads_writes(
			(ack.receivers.len() as u64).saturating_mul(MAX_PRUNE_PER_CALL.saturating_add(4)),
			(ack.receivers.len() as u64).saturating_mul(MAX_PRUNE_PER_CALL.saturating_add(4)),
		))]
		pub fn note_consumed(origin: OriginFor<T>, ack: ConsumedAck) -> DispatchResult {
			ensure_none(origin)?;
			ensure!(ack.receivers.len() <= MAX_ACKS_PER_CALL, Error::<T>::TooManyAcks);

			let state = T::RelayState::current_relay_chain_state();
			let reader =
				RelayChainStateProof::new(T::SelfParaId::get(), state.state_root, ack.proof)
					.map_err(|_| Error::<T>::InvalidRelayProof)?;

			let source = T::SelfParaId::get();
			for receiver in ack.receivers {
				// Relay `RequiresEntry { root, block }` decodes field-for-field as `(H256, block)`.
				let entry: Option<(H256, relay_chain::BlockNumber)> = reader
					.read_optional_entry(&super::latest_requires_key(source, receiver))
					.map_err(|_| Error::<T>::InvalidRelayProof)?;
				if let Some((root, block)) = entry {
					// K-deep finality gate: ignore acks too recent to be revert-safe.
					if state.number.saturating_sub(block) >= T::AckFinalityDepth::get() {
						Self::apply_ack(receiver, root);
					}
				}
			}
			Ok(())
		}
	}

	/// `note_consumed` is an *optional* inherent: the collator fetches relay-verified acks
	/// off-chain, builds the relay state proof, and embeds it in the block. The runtime
	/// re-verifies the proof deterministically. No data ⇒ no inherent.
	#[pallet::inherent]
	impl<T: Config> ProvideInherent for Pallet<T> {
		type Call = Call<T>;
		type Error = sp_inherents::MakeFatalError<()>;
		const INHERENT_IDENTIFIER: InherentIdentifier = INHERENT_IDENTIFIER;

		fn create_inherent(data: &sp_inherents::InherentData) -> Option<Self::Call> {
			let ack = data.get_data::<ConsumedAck>(&Self::INHERENT_IDENTIFIER).ok().flatten()?;
			if ack.receivers.is_empty() {
				return None;
			}
			Some(Call::note_consumed { ack })
		}

		fn is_inherent(call: &Self::Call) -> bool {
			matches!(call, Call::note_consumed { .. })
		}
	}

	impl<T: Config> Pallet<T> {
		/// Record outbound messages in the speculative MMR.
		pub fn record_outbound_messages(dest: ParaId, payloads: Vec<Vec<u8>>) {
			let count = payloads.len() as u32;
			let mut state = OutgoingMMRState::<T>::get(&dest);
			let position_before = state.leaf_count;

			let mut mmr = Mmr::<SpecHasher>::from_parts(state.peaks, state.leaf_count);
			// Persistent MMR mirror: same leaves, nodes written to `OutgoingMmrNodes` so proofs can
			// be generated later without replaying payloads.
			let mut pmmr = MMR::<H256, SpecMerge<SpecHasher>, OutboxStore<T>>::new(
				state.mmr_size,
				OutboxStore::new(dest),
			);
			for payload in payloads {
				let position = mmr.size();
				let leaf = message_leaf::<T>(dest, position, &payload);
				OutgoingMessages::<T>::insert(dest, position, &payload);
				mmr.append(leaf);
				pmmr.push(leaf)
					.expect("OutboxStore reads are infallible; MMR push cannot fail; qed");
			}
			let (peaks, size) = mmr.into_parts();
			state.peaks = peaks;
			state.leaf_count = size;
			state.mmr_size = pmmr.mmr_size();
			pmmr.commit()
				.expect("OutboxStore writes are infallible; MMR commit cannot fail; qed");

			OutgoingMMRState::<T>::insert(dest, state);

			// Backpressure signal: emit `BacklogCapReached` once, when this recording pushes the
			// unconsumed backlog up to the cap (a below→at-cap transition). While at the cap the
			// destination is excluded from `take_outbound_messages`, so it isn't recorded again
			// until the receiver drains it below the cap — no per-block event spam.
			let pruned = PrunedUpTo::<T>::get(&dest);
			let cap = T::MaxBacklogPerDestination::get();
			if position_before.saturating_sub(pruned) < cap && size.saturating_sub(pruned) >= cap {
				Self::deposit_event(Event::BacklogCapReached { destination: dest });
			}

			// Mark this destination's root as changed so it is included in the next block's
			// delta `provides`. Bounded by `MAX_DESTINATIONS_PER_BLOCK` (the same bound as
			// `ProvidesCommitment`); a full set means more distinct destinations were touched
			// in one block than the commitment can carry, so surface it rather than drop quietly.
			PendingProvides::<T>::mutate(|set| {
				if set.try_insert(dest).is_err() {
					log::warn!(
						target: "speculative::outbox",
						"PendingProvides full ({} dests); dropping dest={:?} from provides",
						MAX_DESTINATIONS_PER_BLOCK, dest,
					);
				}
			});
			log::debug!(
				target: "speculative::outbox",
				"recorded {} message(s) to dest={:?} positions {}..{}",
				count, dest, position_before, position_before + count as u64,
			);
			Self::deposit_event(Event::MessagesRecorded { destination: dest, count });
		}
	}
}

impl<T: Config> Pallet<T> {
	/// Compute the flat provides commitment for *this* block: the sorted
	/// `(destination, subtree_root)` set over only the destinations whose root changed in the
	/// previous block (the delta), read from the [`ProvidesThisBlock`] snapshot. Unchanged
	/// destinations are not re-committed every block — the relay retains their last root in its
	/// provides window (count-based eviction), and stale receivers bridge via a late-block proof.
	/// `None` when no destination changed.
	pub fn compute_provides() -> Option<ProvidesCommitment> {
		let entries = ProvidesThisBlock::<T>::get().into_iter().filter_map(|dest| {
			let state = OutgoingMMRState::<T>::get(&dest);
			(state.leaf_count > 0).then(|| (dest, root_from_peaks::<SpecHasher>(&state.peaks)))
		});

		let set = ProvidesCommitment::try_from_iter(entries).ok()?;
		if set.is_empty() {
			None
		} else {
			Some(set)
		}
	}

	/// Whether `dest` is at its unconsumed-backlog cap, i.e. the number of
	/// stored-but-not-yet-pruned payloads (`leaf_count - PrunedUpTo`) has reached
	/// [`Config::MaxBacklogPerDestination`]. While full, new messages to `dest` fall back to plain
	/// HRMP rather than growing storage unboundedly.
	pub(crate) fn backlog_full(dest: ParaId) -> bool {
		let leaf_count = OutgoingMMRState::<T>::get(&dest).leaf_count;
		let pruned = PrunedUpTo::<T>::get(&dest);
		leaf_count.saturating_sub(pruned) >= T::MaxBacklogPerDestination::get()
	}

	/// Apply a receiver's acknowledged `requires` root for `dest`: advance the consumed watermark
	/// to the leaf position that root commits to and prune acknowledged payloads (capped).
	///
	/// Returns `true` if the watermark advanced. No-op (returns `false`) when the root is unknown
	/// (e.g. already pruned, or never committed) or does not represent forward progress — the
	/// watermark is strictly monotonic, so a stale or under-reporting ack can never regress it.
	///
	/// Trust: callers must only pass roots that the relay has verified the receiver consumed (the
	/// `note_consumed` extrinsic in Phase 3 enforces this via a relay state proof). Because the
	/// watermark only advances and roots are sender-produced, a malicious receiver can at worst
	/// under-report (pruning less) — never over-report.
	pub fn apply_ack(dest: ParaId, acked_root: H256) -> bool {
		let Some((position, _block)) = CommittedRootPosition::<T>::get(dest, acked_root) else {
			return false;
		};
		if position <= ConsumedWatermark::<T>::get(dest) {
			return false;
		}
		ConsumedWatermark::<T>::insert(dest, position);
		Self::prune_consumed(dest, MAX_PRUNE_PER_CALL);
		Self::prune_nodes(dest, MAX_PRUNE_PER_CALL);
		Self::deposit_event(Event::ConsumedWatermarkAdvanced { destination: dest, position });
		true
	}

	/// Delete up to `max` consumed payloads for `dest` (positions in `[PrunedUpTo, watermark)`),
	/// advancing the prune cursor, and drop now-obsolete root-index entries. Returns the number of
	/// payloads deleted. Safe to call repeatedly; it drains the backlog incrementally.
	pub(crate) fn prune_consumed(dest: ParaId, max: u64) -> u64 {
		let watermark = ConsumedWatermark::<T>::get(dest);
		let start = PrunedUpTo::<T>::get(dest);
		if start >= watermark {
			return 0;
		}
		let end = watermark.min(start.saturating_add(max));
		for pos in start..end {
			OutgoingMessages::<T>::remove(dest, pos);
		}
		PrunedUpTo::<T>::insert(dest, end);

		// Drop root-index entries strictly below the watermark — no future (monotonic) ack can
		// reference them. The entry *at* the watermark (the current consumption frontier) is kept:
		// the receiver's next late-block proof builds an extension from exactly that root. Capped
		// to bound the scan.
		let obsolete: Vec<H256> = CommittedRootPosition::<T>::iter_prefix(dest)
			.filter(|(_, (leaf_count, _))| *leaf_count < watermark)
			.map(|(root, _)| root)
			.take(max as usize)
			.collect();
		for root in obsolete {
			CommittedRootPosition::<T>::remove(dest, root);
		}

		end - start
	}

	/// Reclaim persistent MMR nodes inside fully-consumed subtrees for `dest`, advancing
	/// [`NodePrunedUpTo`] by up to `max_leaves`. Keeps only the peaks of the consumed prefix (the
	/// witness frontier) so inclusion / late-block proofs for un-consumed leaves still verify, and
	/// keeps every node at or beyond the prefix. Returns the number of nodes removed.
	///
	/// Correctness: for leaves at index `>= W` the only witnesses from the consumed region `[0, W)`
	/// are the peaks of the prefix MMR over `W` leaves (`get_peaks(leaf_index_to_mmr_size(W))`);
	/// every other node there lies strictly inside a completed left subtree, summarised by its peak,
	/// and is never read again by `gen_proof` or by `push` (which only touches current peaks).
	pub(crate) fn prune_nodes(dest: ParaId, max_leaves: u64) -> u64 {
		use mmr_lib::helper::{get_peaks, leaf_index_to_mmr_size};

		let watermark = ConsumedWatermark::<T>::get(dest);
		let pruned_to = NodePrunedUpTo::<T>::get(dest);
		if pruned_to >= watermark {
			return 0;
		}
		let target = watermark.min(pruned_to.saturating_add(max_leaves));
		if target == 0 {
			return 0;
		}

		// Size (node count) of the MMR over the first `leaves` leaves; `leaf_index_to_mmr_size` takes
		// a 0-based leaf *index*, so `leaves - 1`. Positions `[0, prefix_size)` are exactly those
		// leaves' nodes.
		let prefix_size =
			|leaves: u64| if leaves == 0 { 0 } else { leaf_index_to_mmr_size(leaves - 1) };
		let old_prefix = prefix_size(pruned_to);
		let new_prefix = prefix_size(target);
		let keep: BTreeSet<u64> = get_peaks(new_prefix).into_iter().collect();

		let mut removed = 0u64;
		// Former prefix peaks that are no longer prefix peaks have merged into larger subtrees and
		// are now summarised by a `keep` peak — drop them.
		for pos in get_peaks(old_prefix) {
			if !keep.contains(&pos) && OutgoingMmrNodes::<T>::take(dest, pos).is_some() {
				removed = removed.saturating_add(1);
			}
		}
		// Newly-completed prefix range: delete everything that is not a kept peak.
		for pos in old_prefix..new_prefix {
			if !keep.contains(&pos) && OutgoingMmrNodes::<T>::take(dest, pos).is_some() {
				removed = removed.saturating_add(1);
			}
		}

		NodePrunedUpTo::<T>::insert(dest, target);
		removed
	}

	/// Get the MMR subtree root and leaf count for a destination.
	pub fn destination_state(dest: ParaId) -> Option<(H256, u64)> {
		let state = OutgoingMMRState::<T>::get(&dest);
		if state.leaf_count == 0 {
			return None;
		}
		let root = root_from_peaks::<SpecHasher>(&state.peaks);
		Some((root, state.leaf_count))
	}

	/// Read payload bytes for a destination starting at `from_position`.
	pub fn outbound_messages(
		dest: ParaId,
		from_position: u64,
		max_messages: u32,
	) -> Vec<(u64, Vec<u8>)> {
		let leaf_count = OutgoingMMRState::<T>::get(&dest).leaf_count;
		let end = leaf_count.min(from_position + max_messages as u64);
		(from_position..end)
			.filter_map(|pos| OutgoingMessages::<T>::get(dest, pos).map(|p| (pos, p)))
			.collect()
	}

	/// Read a slice of outbound messages along with a combined MMR inclusion proof
	/// against the per-destination `subtree_root`. The receiver verifies the returned
	/// proof with `MerkleProof::<_, SpecMerge>::new(mmr_size, proof).verify(root, leaves)`.
	///
	/// Returns `None` if the destination has no messages, the requested slice is empty, or a
	/// requested payload has already been pruned (i.e. `from_position` is below the consumed
	/// watermark — callers should request only un-consumed positions).
	///
	/// Cost: O(log n + slice) — the proof is generated from the persistent node store
	/// ([`OutgoingMmrNodes`]); payloads are read only for the requested slice, never replayed
	/// from position 0, so this works after consumed payloads have been pruned.
	pub fn outbound_messages_with_proof(
		dest: ParaId,
		from_position: u64,
		max_messages: u32,
	) -> Option<(Vec<(u64, Vec<u8>)>, u64, Vec<H256>)> {
		let state = OutgoingMMRState::<T>::get(&dest);
		if state.leaf_count == 0 {
			return None;
		}
		let end = state.leaf_count.min(from_position.saturating_add(max_messages as u64));
		if end <= from_position {
			return None;
		}

		// Read only the requested payloads; bail if any has been pruned.
		let mut messages: Vec<(u64, Vec<u8>)> = Vec::new();
		for pos in from_position..end {
			messages.push((pos, OutgoingMessages::<T>::get(dest, pos)?));
		}

		// Proof witness comes from the persistent node store — no payload replay.
		let mmr = MMR::<H256, SpecMerge<SpecHasher>, OutboxStore<T>>::new(
			state.mmr_size,
			OutboxStore::new(dest),
		);
		let positions: Vec<u64> = (from_position..end).map(leaf_index_to_pos).collect();
		let proof = mmr.gen_proof(positions).ok()?;
		Some((messages, state.mmr_size, proof.proof_items().to_vec()))
	}

	/// Generate a late block proof for a receiver `dest` that built against an older
	/// per-destination subtree root. The proof shows that the source's subtree for
	/// `dest` was only appended to between `old_subtree_root` and the current root.
	pub fn generate_late_block_proof(
		dest: ParaId,
		old_subtree_root: H256,
	) -> Option<LateBlockProof> {
		// Map the old subtree root to its leaf count via the durable, watermark-pruned root index, so
		// a receiver building against an arbitrarily old — but not-yet-consumed — root can be served.
		let (old_leaf_count, _) = CommittedRootPosition::<T>::get(dest, old_subtree_root)?;

		let current = OutgoingMMRState::<T>::get(&dest);
		let new_subtree_root = root_from_peaks::<SpecHasher>(&current.peaks);

		let subtree_extension = if current.leaf_count > old_leaf_count {
			// Prove the appended leaves [old_leaf_count, current) against the persistent node
			// store. Only the appended payloads are read (all >= the consumed watermark, so
			// retained); nothing is replayed from position 0.
			let mmr = MMR::<H256, SpecMerge<SpecHasher>, OutboxStore<T>>::new(
				current.mmr_size,
				OutboxStore::new(dest),
			);
			let mut incremental: Vec<H256> = Vec::new();
			for pos in old_leaf_count..current.leaf_count {
				let payload = OutgoingMessages::<T>::get(dest, pos)?;
				incremental.push(message_leaf::<T>(dest, pos, &payload));
			}
			let positions: Vec<u64> =
				(old_leaf_count..current.leaf_count).map(leaf_index_to_pos).collect();
			let proof = mmr.gen_proof(positions).ok()?;
			Some(SubtreeExtension {
				new_mmr_size: current.mmr_size,
				proof: proof.proof_items().to_vec(),
				incremental,
			})
		} else {
			None
		};

		// `source` is *this* (the sender) para id — it is matched against the
		// receiver's `requires[source]` entry in `apply_messaging_proofs`.
		Some(LateBlockProof {
			source: T::SelfParaId::get(),
			old_subtree_root,
			new_subtree_root,
			subtree_extension,
		})
	}

	/// Find the block number at which `dest`'s subtree root was `subtree_root` (from the durable root
	/// index; available while the root is at or above the consumed watermark).
	pub fn block_number_for_subtree_root(
		dest: ParaId,
		subtree_root: H256,
	) -> Option<BlockNumberFor<T>> {
		CommittedRootPosition::<T>::get(dest, subtree_root).map(|(_, block)| block)
	}
}

impl<T: Config> XcmpMessageSource for Pallet<T> {
	fn take_outbound_messages(
		maximum_channels: usize,
		excluded_recipients: &[ParaId],
	) -> Vec<(ParaId, Vec<u8>)> {
		// Backpressure: keep destinations already at their backlog cap out of the inner take, so
		// their outbound messages stay buffered in the inner queue (`XcmpQueue`) and the existing
		// XCMP congestion/fee machinery throttles the origin. Self-heals once the receiver drains
		// the backlog below the cap. (`BacklogCapReached` is emitted edge-triggered in
		// `record_outbound_messages` when a destination crosses into the capped state.)
		let mut excluded: Vec<ParaId> = excluded_recipients.to_vec();
		for (dest, _) in OutgoingMMRState::<T>::iter() {
			if Pallet::<T>::backlog_full(dest) {
				excluded.push(dest);
			}
		}

		let messages =
			T::InnerXcmpMessageSource::take_outbound_messages(maximum_channels, &excluded);
		for (dest, data) in messages {
			Pallet::<T>::record_outbound_messages(dest, vec![data]);
		}

		// Messages are delivered exclusively via the speculative pathway; returning them here would
		// also place them in `horizontal_messages`, causing double processing on the receiver.
		Vec::new()
	}
}

// ── Helpers ──

/// Relay storage key for `ParaInclusion::LatestRequires(source, receiver)` (a `StorageDoubleMap`
/// hashed `Twox64Concat` on both keys). The pallet name must match the relay runtime's
/// `construct_runtime!` entry (`ParaInclusion`); a mismatch would make every lookup miss.
pub fn latest_requires_key(source: ParaId, receiver: ParaId) -> Vec<u8> {
	let mut key =
		frame_support::storage::storage_prefix(b"ParaInclusion", b"LatestRequires").to_vec();
	for id in [source, receiver] {
		let encoded = id.encode();
		key.extend_from_slice(&sp_io::hashing::twox_64(&encoded));
		key.extend_from_slice(&encoded);
	}
	key
}

/// Hash a message into its MMR leaf, binding `(source, destination, position)` via
/// `OutgoingMessage::hash_leaf` (`blake2_256`, domain-tagged).
fn message_leaf<T: Config>(dest: ParaId, position: u64, payload: &[u8]) -> H256 {
	let bounded: BoundedVec<u8, MaxSpeculativeMessageLen> =
		BoundedVec::try_from(payload.to_vec()).unwrap_or_default();
	OutgoingMessage::new(T::SelfParaId::get(), dest, position, bounded).hash_leaf::<SpecHasher>()
}

#[cfg(test)]
mod mock;

#[cfg(test)]
mod rotation_tests {
	use crate::{
		mock::{new_test_ext, SpeculativeOutbox, Test},
		OutgoingMMRState, PendingProvides, ProvidesThisBlock,
	};
	use cumulus_primitives_core::ParaId;
	use frame_support::traits::OnInitialize;

	const DEST_A: u32 = 3000;
	const DEST_B: u32 = 4000;

	/// Advance to the next block by running the pallet's `on_initialize`, which performs the
	/// `PendingProvides` -> `ProvidesThisBlock` rotation.
	fn rotate_into(block: u64) {
		SpeculativeOutbox::on_initialize(block);
	}

	#[test]
	fn delta_provides_appears_next_block_then_clears() {
		new_test_ext().execute_with(|| {
			// Block 1: record a message to DEST_A. It is accumulated in `PendingProvides`
			// but not yet visible in `provides` (nothing has been rotated in).
			rotate_into(1);
			SpeculativeOutbox::record_outbound_messages(ParaId::from(DEST_A), vec![b"a".to_vec()]);
			assert!(PendingProvides::<Test>::get().contains(&ParaId::from(DEST_A)));
			assert!(SpeculativeOutbox::compute_provides().is_none());

			// Block 2 (N+1): rotation promotes DEST_A into the snapshot, so it shows up in
			// `provides` exactly once, with the destination's current subtree root.
			rotate_into(2);
			assert!(ProvidesThisBlock::<Test>::get().contains(&ParaId::from(DEST_A)));
			assert!(PendingProvides::<Test>::get().is_empty());
			let provides = SpeculativeOutbox::compute_provides().expect("delta has one entry");
			assert_eq!(provides.len(), 1);
			let (expected_root, _) =
				SpeculativeOutbox::destination_state(ParaId::from(DEST_A)).unwrap();
			assert_eq!(provides.get(ParaId::from(DEST_A)), Some(&expected_root));

			// Block 3 (N+2): no new records, so the destination is no longer re-committed —
			// `provides` is empty even though the MMR state still exists.
			rotate_into(3);
			assert!(SpeculativeOutbox::compute_provides().is_none());
			assert!(OutgoingMMRState::<Test>::get(ParaId::from(DEST_A)).leaf_count > 0);
		});
	}

	#[test]
	fn delta_dedups_and_batches_destinations_per_block() {
		new_test_ext().execute_with(|| {
			rotate_into(1);
			// Two messages to DEST_A and one to DEST_B in the same block.
			SpeculativeOutbox::record_outbound_messages(
				ParaId::from(DEST_A),
				vec![b"a1".to_vec(), b"a2".to_vec()],
			);
			SpeculativeOutbox::record_outbound_messages(ParaId::from(DEST_A), vec![b"a3".to_vec()]);
			SpeculativeOutbox::record_outbound_messages(ParaId::from(DEST_B), vec![b"b1".to_vec()]);

			// DEST_A appears once despite two record calls (set dedups).
			assert_eq!(PendingProvides::<Test>::get().len(), 2);

			rotate_into(2);
			let provides = SpeculativeOutbox::compute_provides().expect("two entries");
			assert_eq!(provides.len(), 2);
			assert!(provides.get(ParaId::from(DEST_A)).is_some());
			assert!(provides.get(ParaId::from(DEST_B)).is_some());
		});
	}
}

#[cfg(test)]
mod watermark_tests {
	use crate::{
		mock::{new_test_ext, SpeculativeOutbox, Test},
		CommittedRootPosition, ConsumedWatermark, OutgoingMessages, PrunedUpTo, MAX_PRUNE_PER_CALL,
	};
	use cumulus_primitives_core::ParaId;
	use cumulus_primitives_spec_messaging::{mmr::SpecMerge, OutgoingMessage, SpecHasher};
	use frame_support::traits::{OnFinalize, OnIdle};
	use mmr_lib::{leaf_index_to_pos, MerkleProof};
	use sp_core::H256;
	use sp_runtime::{BoundedVec, Weight};

	const DEST: u32 = 3000;
	const SOURCE: u32 = 1000; // == mock `OutboxParaId`

	/// Recompute the MMR leaf for `(SOURCE, DEST, pos, payload)` as the pallet does.
	fn leaf_at(pos: u64, payload: &[u8]) -> H256 {
		let bounded = BoundedVec::try_from(payload.to_vec()).unwrap();
		OutgoingMessage::new(SOURCE.into(), DEST.into(), pos, bounded).hash_leaf::<SpecHasher>()
	}

	/// Record `payloads` to `DEST` and finalize block `block` (which commits the current root into
	/// `CommittedRootPosition`). Returns the committed end-of-block root.
	fn record_and_finalize(block: u64, payloads: Vec<Vec<u8>>) -> H256 {
		SpeculativeOutbox::record_outbound_messages(ParaId::from(DEST), payloads);
		SpeculativeOutbox::on_finalize(block);
		SpeculativeOutbox::destination_state(ParaId::from(DEST)).unwrap().0
	}

	fn payloads(range: std::ops::Range<u32>) -> Vec<Vec<u8>> {
		range.map(|i| i.to_le_bytes().to_vec()).collect()
	}

	#[test]
	fn apply_ack_advances_watermark_and_prunes() {
		new_test_ext().execute_with(|| {
			let dest = ParaId::from(DEST);
			let root = record_and_finalize(1, payloads(0..3));
			assert_eq!(CommittedRootPosition::<Test>::get(dest, root), Some((3, 1)));

			assert!(SpeculativeOutbox::apply_ack(dest, root));
			assert_eq!(ConsumedWatermark::<Test>::get(dest), 3);
			assert_eq!(PrunedUpTo::<Test>::get(dest), 3);
			// All three consumed payloads pruned.
			for pos in 0..3 {
				assert!(!OutgoingMessages::<Test>::contains_key(dest, pos));
			}
		});
	}

	#[test]
	fn apply_ack_prunes_only_consumed_prefix() {
		new_test_ext().execute_with(|| {
			let dest = ParaId::from(DEST);
			let root1 = record_and_finalize(1, payloads(0..1)); // leaf_count 1
			let _root3 = record_and_finalize(2, payloads(1..3)); // leaf_count 3

			// Acknowledge only up to position 1: prune position 0, retain 1 and 2.
			assert!(SpeculativeOutbox::apply_ack(dest, root1));
			assert_eq!(ConsumedWatermark::<Test>::get(dest), 1);
			assert!(!OutgoingMessages::<Test>::contains_key(dest, 0));
			assert!(OutgoingMessages::<Test>::contains_key(dest, 1));
			assert!(OutgoingMessages::<Test>::contains_key(dest, 2));
		});
	}

	#[test]
	fn apply_ack_is_monotonic_and_ignores_unknown_roots() {
		new_test_ext().execute_with(|| {
			let dest = ParaId::from(DEST);
			let root1 = record_and_finalize(1, payloads(0..1));
			let root3 = record_and_finalize(2, payloads(1..3));

			assert!(SpeculativeOutbox::apply_ack(dest, root3)); // watermark -> 3
													   // A stale (lower) ack does not regress the watermark.
			assert!(!SpeculativeOutbox::apply_ack(dest, root1));
			assert_eq!(ConsumedWatermark::<Test>::get(dest), 3);
			// An unknown root is a no-op.
			assert!(!SpeculativeOutbox::apply_ack(dest, H256::repeat_byte(0xab)));
			assert_eq!(ConsumedWatermark::<Test>::get(dest), 3);
		});
	}

	#[test]
	fn no_ack_retains_all_payloads() {
		new_test_ext().execute_with(|| {
			let dest = ParaId::from(DEST);
			let _root = record_and_finalize(1, payloads(0..5));
			// A slow receiver that never acks: nothing is pruned regardless of block progress.
			SpeculativeOutbox::on_finalize(2);
			SpeculativeOutbox::on_idle(2, Weight::MAX);
			assert_eq!(PrunedUpTo::<Test>::get(dest), 0);
			for pos in 0..5 {
				assert!(OutgoingMessages::<Test>::contains_key(dest, pos));
			}
		});
	}

	#[test]
	fn proofs_survive_payload_pruning() {
		new_test_ext().execute_with(|| {
			let dest = ParaId::from(DEST);
			// Commit a root at leaf_count 3 (to ack against), then extend to 5.
			SpeculativeOutbox::record_outbound_messages(dest, payloads(0..3));
			SpeculativeOutbox::on_finalize(1);
			let root3 = SpeculativeOutbox::destination_state(dest).unwrap().0;
			SpeculativeOutbox::record_outbound_messages(dest, payloads(3..5));
			SpeculativeOutbox::on_finalize(2);
			let (root5, leaf_count) = SpeculativeOutbox::destination_state(dest).unwrap();
			assert_eq!(leaf_count, 5);

			// Acknowledge up to root3 → payloads [0,3) pruned.
			assert!(SpeculativeOutbox::apply_ack(dest, root3));
			assert!(!OutgoingMessages::<Test>::contains_key(dest, 0));

			// An inclusion proof for the retained tail [3,5) still generates from the node store
			// and verifies against the current root — despite the consumed payloads being gone.
			let (msgs, mmr_size, proof) =
				SpeculativeOutbox::outbound_messages_with_proof(dest, 3, 10).unwrap();
			assert_eq!(msgs.iter().map(|(p, _)| *p).collect::<Vec<_>>(), vec![3, 4]);
			let leaves: Vec<(u64, H256)> = msgs
				.iter()
				.map(|(pos, payload)| (leaf_index_to_pos(*pos), leaf_at(*pos, payload)))
				.collect();
			let mp = MerkleProof::<H256, SpecMerge<SpecHasher>>::new(mmr_size, proof);
			assert!(mp.verify(root5, leaves).unwrap());

			// And the frontier root (root3, at the watermark) is retained for the next late proof.
			assert_eq!(CommittedRootPosition::<Test>::get(dest, root3), Some((3, 1)));
		});
	}

	#[test]
	fn node_pruning_keeps_proofs_verifiable() {
		use crate::{NodePrunedUpTo, OutgoingMmrNodes};
		// For a range of MMR sizes, advance the watermark step by step (pruning nodes each time) and
		// assert that every un-consumed leaf is still provable against the current root — i.e. node
		// pruning never removes a witness.
		for n in [1u64, 2, 3, 5, 8, 13, 16] {
			new_test_ext().execute_with(|| {
				let dest = ParaId::from(DEST);
				let mut roots = vec![H256::zero()]; // index 0 unused
				for i in 1..=n {
					SpeculativeOutbox::record_outbound_messages(dest, payloads(0..1));
					SpeculativeOutbox::on_finalize(i);
					roots.push(SpeculativeOutbox::destination_state(dest).unwrap().0);
				}
				let final_root = roots[n as usize];

				for w in 1..n {
					assert!(SpeculativeOutbox::apply_ack(dest, roots[w as usize]));
					// Drain node pruning fully for this watermark.
					while SpeculativeOutbox::prune_nodes(dest, 1000) > 0 {}
					assert_eq!(NodePrunedUpTo::<Test>::get(dest), w);

					for from in w..n {
						let (msgs, mmr_size, proof) =
							SpeculativeOutbox::outbound_messages_with_proof(dest, from, 1000)
								.unwrap_or_else(|| panic!("proof missing: n={n} w={w} from={from}"));
						let leaves: Vec<(u64, H256)> = msgs
							.iter()
							.map(|(pos, payload)| (leaf_index_to_pos(*pos), leaf_at(*pos, payload)))
							.collect();
						let mp = MerkleProof::<H256, SpecMerge<SpecHasher>>::new(mmr_size, proof);
						assert!(
							mp.verify(final_root, leaves).unwrap(),
							"verify failed: n={n} w={w} from={from}"
						);
					}
				}

				// Sanity: pruning actually removed nodes for the larger sizes.
				if n >= 8 {
					let kept = OutgoingMmrNodes::<Test>::iter_prefix(dest).count() as u64;
					assert!(kept < 2 * n, "expected node store to shrink: n={n} kept={kept}");
				}
			});
		}
	}

	#[test]
	fn backlog_cap_gates_on_unconsumed_then_reopens_after_ack() {
		new_test_ext().execute_with(|| {
			let dest = ParaId::from(DEST);
			// Mock cap is 5. Record up to the cap: backlog becomes full.
			let root = record_and_finalize(1, payloads(0..5));
			assert!(SpeculativeOutbox::backlog_full(dest));

			// Acknowledging consumption prunes payloads and reopens the channel.
			assert!(SpeculativeOutbox::apply_ack(dest, root));
			assert!(!SpeculativeOutbox::backlog_full(dest));
		});
	}

	#[test]
	fn backlog_not_full_below_cap() {
		new_test_ext().execute_with(|| {
			let dest = ParaId::from(DEST);
			let _root = record_and_finalize(1, payloads(0..4));
			assert!(!SpeculativeOutbox::backlog_full(dest));
		});
	}

	#[test]
	fn capped_prune_resumes_via_on_idle() {
		new_test_ext().execute_with(|| {
			let dest = ParaId::from(DEST);
			let total = MAX_PRUNE_PER_CALL + 50;
			let root = record_and_finalize(1, payloads(0..total as u32));

			// One ack advances the watermark fully but only prunes a capped chunk inline.
			assert!(SpeculativeOutbox::apply_ack(dest, root));
			assert_eq!(ConsumedWatermark::<Test>::get(dest), total);
			assert_eq!(PrunedUpTo::<Test>::get(dest), MAX_PRUNE_PER_CALL);

			// on_idle drains the remaining backlog.
			SpeculativeOutbox::on_idle(2, Weight::MAX);
			assert_eq!(PrunedUpTo::<Test>::get(dest), total);
			for pos in 0..total {
				assert!(!OutgoingMessages::<Test>::contains_key(dest, pos));
			}
		});
	}
}

#[cfg(test)]
mod ack_tests {
	use crate::{
		latest_requires_key,
		mock::{new_test_ext, set_relay_state, RuntimeOrigin, SpeculativeOutbox, Test},
		ConsumedAck, ConsumedWatermark, Error,
	};
	use codec::Encode;
	use cumulus_primitives_core::ParaId;
	use cumulus_test_relay_sproof_builder::RelayStateSproofBuilder;
	use frame_support::{assert_noop, assert_ok, traits::OnFinalize};
	use sp_core::H256;

	const SOURCE: u32 = 1000; // == mock `OutboxParaId` (this parachain)
	const RECEIVER: u32 = 3000;

	/// Record three messages to `RECEIVER` and finalize, returning the committed root (leaf_count
	/// 3).
	fn seed_messages() -> H256 {
		SpeculativeOutbox::record_outbound_messages(
			ParaId::from(RECEIVER),
			vec![b"a".to_vec(), b"b".to_vec(), b"c".to_vec()],
		);
		SpeculativeOutbox::on_finalize(1);
		SpeculativeOutbox::destination_state(ParaId::from(RECEIVER)).unwrap().0
	}

	/// Build a relay state proof committing `LatestRequires<SOURCE, RECEIVER> = (root, block)`.
	fn relay_proof_for(root: H256, block: u32) -> (H256, sp_trie::StorageProof) {
		let mut sproof = RelayStateSproofBuilder::default();
		let key = latest_requires_key(ParaId::from(SOURCE), ParaId::from(RECEIVER));
		sproof.additional_key_values.push((key, (root, block).encode()));
		sproof.into_state_root_and_proof()
	}

	#[test]
	fn note_consumed_advances_watermark_from_relay_proof() {
		new_test_ext().execute_with(|| {
			let receiver = ParaId::from(RECEIVER);
			let root = seed_messages();
			let (state_root, proof) = relay_proof_for(root, 1);

			// Relay parent at block 5: 5 - 1 = 4 >= K (2), so the ack passes the finality gate.
			set_relay_state(5, state_root);
			assert_ok!(SpeculativeOutbox::note_consumed(
				RuntimeOrigin::none(),
				ConsumedAck { proof, receivers: vec![receiver] },
			));
			assert_eq!(ConsumedWatermark::<Test>::get(receiver), 3);
		});
	}

	#[test]
	fn note_consumed_ignores_acks_within_finality_depth() {
		new_test_ext().execute_with(|| {
			let receiver = ParaId::from(RECEIVER);
			let root = seed_messages();
			let (state_root, proof) = relay_proof_for(root, 1);

			// Relay parent at block 2: 2 - 1 = 1 < K (2) — too recent to be revert-safe.
			set_relay_state(2, state_root);
			assert_ok!(SpeculativeOutbox::note_consumed(
				RuntimeOrigin::none(),
				ConsumedAck { proof, receivers: vec![receiver] },
			));
			assert_eq!(ConsumedWatermark::<Test>::get(receiver), 0);
		});
	}

	#[test]
	fn note_consumed_rejects_proof_not_matching_relay_root() {
		new_test_ext().execute_with(|| {
			let receiver = ParaId::from(RECEIVER);
			let root = seed_messages();
			let (_state_root, proof) = relay_proof_for(root, 1);

			// A relay state root that does not match the proof must be rejected.
			set_relay_state(5, H256::repeat_byte(0xff));
			assert_noop!(
				SpeculativeOutbox::note_consumed(
					RuntimeOrigin::none(),
					ConsumedAck { proof, receivers: vec![receiver] },
				),
				Error::<Test>::InvalidRelayProof,
			);
		});
	}

	#[test]
	fn note_consumed_is_noop_for_absent_ack() {
		new_test_ext().execute_with(|| {
			let receiver = ParaId::from(RECEIVER);
			let _root = seed_messages();
			// Proof commits an ack for a *different* receiver, so RECEIVER's lookup is absent.
			let mut sproof = RelayStateSproofBuilder::default();
			let key = latest_requires_key(ParaId::from(SOURCE), ParaId::from(9999));
			sproof.additional_key_values.push((key, (H256::repeat_byte(1), 1u32).encode()));
			let (state_root, proof) = sproof.into_state_root_and_proof();

			set_relay_state(5, state_root);
			assert_ok!(SpeculativeOutbox::note_consumed(
				RuntimeOrigin::none(),
				ConsumedAck { proof, receivers: vec![receiver] },
			));
			assert_eq!(ConsumedWatermark::<Test>::get(receiver), 0);
		});
	}
}

#[cfg(test)]
mod tests {
	use super::*;
	use mmr_lib::util::{MemMMR, MemStore};

	fn leaf(source: u32, dest: u32, position: u64, payload: &[u8]) -> H256 {
		let bounded = BoundedVec::try_from(payload.to_vec()).unwrap();
		OutgoingMessage::new(source.into(), dest.into(), position, bounded)
			.hash_leaf::<SpecHasher>()
	}

	#[test]
	fn peaks_root_matches_mmr_lib() {
		let leaves = [leaf(1, 2, 0, b"msg1"), leaf(1, 2, 1, b"msg2"), leaf(1, 2, 2, b"msg3")];

		// Build using the peaks-only accumulator (same as the pallet).
		let mut acc = Mmr::<SpecHasher>::new();
		for l in &leaves {
			acc.append(*l);
		}

		// Reference: mmr_lib in-memory MMR with the same SpecMerge.
		let store = MemStore::<H256>::default();
		let mut mmr = MemMMR::<H256, SpecMerge<SpecHasher>>::new(0, &store);
		for l in &leaves {
			mmr.push(*l).unwrap();
		}

		assert_eq!(acc.root(), mmr.get_root().unwrap());
	}
}
