[package]
name = "cumulus-client-spec-msg"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "Speculative Messaging node side: the sender archive, the fetch protocol and the receiver."
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
async-channel = { workspace = true }
async-trait = { workspace = true }
codec = { features = ["derive"], workspace = true, default-features = true }
futures = { workspace = true }
futures-timer = { workspace = true }
log = { workspace = true, default-features = true }
mmr-lib = { workspace = true, default-features = true }
parking_lot = { workspace = true, default-features = true }

# Substrate
sc-client-api = { workspace = true, default-features = true }
sc-network = { workspace = true, default-features = true }
sp-api = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }

# Polkadot
polkadot-core-primitives = { workspace = true, default-features = true }
polkadot-primitives = { workspace = true, default-features = true }

# Cumulus
cumulus-client-collator = { workspace = true, default-features = true }
cumulus-primitives-core = { workspace = true, default-features = true }
cumulus-primitives-spec-messaging = { workspace = true, default-features = true }
cumulus-relay-chain-interface = { workspace = true, default-features = true }

[dev-dependencies]
sp-core = { workspace = true, default-features = true }
