// Copyright (C) Parity Technologies (UK) Ltd.
// This file is part of Polkadot.

// Polkadot is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// Polkadot is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with Polkadot.  If not, see <http://www.gnu.org/licenses/>.

//! Speculative messaging primitives (Phase 1 — inclusion-based messaging).

use alloc::vec::Vec;

use codec::{Decode, DecodeWithMemTracking, Encode};
use scale_info::TypeInfo;

use super::{BlockNumber, Hash, Id};

/// The API version at which speculative messaging support was introduced.
/// Collators and runtimes use this to gate speculative field population.
pub const SPECULATIVE_API_VERSION: u32 = 10;

/// Maximum number of source parachains a receiver can consume from in one block.
/// This bounds the size of `requires` in candidate commitments.
pub const MAX_REQUIRES_PER_BLOCK: usize = 32;

/// A commitment that a parachain provides a set of outbound speculative messages.
/// The root is the top-level Merkle root over all per-destination MMR roots.
#[derive(Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, Eq, Debug, TypeInfo)]
#[cfg_attr(feature = "std", derive(Hash))]
pub struct ProvidesCommitment {
	/// Top-level Merkle root over all per-destination MMR roots.
	pub root: Hash,
}

/// A commitment that a parachain requires messages from a source parachain.
#[derive(Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, Eq, Debug, TypeInfo)]
#[cfg_attr(feature = "std", derive(Hash))]
pub struct RequiresCommitment {
	/// The source parachain whose provides root we expect.
	pub source: Id,
	/// The provides root we built against (the source chain's top-level root at the
	/// block from which we received messages).
	pub expected_root: Hash,
}

/// Deterministic ingress payload carried in the parachain block body.
#[derive(Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, Eq, Debug, TypeInfo)]
pub struct SpeculativeIngress {
	/// Verified batches selected by the collator for this block.
	pub batches: Vec<MessageBatch>,
}

/// A binary-Merkle-tree inclusion proof for one leaf, plus the metadata needed to
/// verify it via `binary_merkle_tree::verify_proof`.
///
/// The leaf bytes themselves are reconstructed by the verifier (e.g. `(para_id,
/// subtree_root).encode()`), so they are not stored in this struct.
#[derive(Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, Eq, Debug, TypeInfo)]
pub struct MerkleSubtreeProof {
	/// Sibling hashes from leaf to root.
	pub proof: Vec<Hash>,
	/// Total number of leaves in the tree (required for odd-leaf promotion handling).
	pub number_of_leaves: u32,
	/// 0-based index of the leaf this proof is for.
	pub leaf_index: u32,
}

/// Combined MMR inclusion proof over a set of leaves, against an MMR root.
///
/// Generated by `mmr_lib::MMR::gen_proof` and verified by `MerkleProof::new(mmr_size,
/// proof).verify(root, leaves)` where `leaves` is `(leaf_pos, leaf_hash)` for each
/// covered leaf.
#[derive(Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, Eq, Debug, TypeInfo)]
pub struct MmrInclusionProof {
	/// Total number of MMR nodes (positions, not leaves) in the MMR at the time the
	/// proof was generated.
	pub mmr_size: u64,
	/// Proof items returned by `gen_proof`.
	pub proof: Vec<Hash>,
}

/// A message batch sent off-chain between collators.
#[derive(Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, Eq, Debug, TypeInfo)]
pub struct MessageBatch {
	/// Source parachain.
	pub source: Id,
	/// Relay-chain block number associated with the source batch.
	pub source_relay_parent_number: BlockNumber,
	/// The top-level provides root for this block.
	pub provides_root: Hash,
	/// The per-destination MMR root for the receiver.
	pub subtree_root: Hash,
	/// Combined MMR inclusion proof over every leaf in `messages`, against `subtree_root`.
	pub messages_proof: MmrInclusionProof,
	/// Merkle proof that `(receiver_para_id, subtree_root)` is the leaf for this
	/// destination in the top-level Merkle tree rooted at `provides_root`.
	pub subtree_inclusion_proof: MerkleSubtreeProof,
	/// The messages, sorted by `position` ascending. Verified collectively by
	/// `messages_proof` against `subtree_root`.
	pub messages: Vec<OutgoingMessage>,
}

/// An individual outbound message with its MMR leaf index. Verified collectively
/// with the rest of the batch via `MessageBatch::messages_proof`.
#[derive(Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, Eq, Debug, TypeInfo)]
pub struct OutgoingMessage {
	/// Zero-based leaf index in the source's per-destination MMR.
	pub position: u64,
	/// Raw XCM message bytes.
	pub payload: Vec<u8>,
}

/// Included in the receiver candidate's PoV when the block was built against
/// an older source root than what's persisted in ProvidesRoots.
#[derive(Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, Eq, Debug, TypeInfo)]
pub struct LateBlockProof {
	/// The source parachain this proof covers.
	pub source: Id,

	/// The provides root the receiver block was built against (the old root
	/// from the batch).
	pub old_provides_root: Hash,
	/// The subtree root the receiver built against (from the old source block).
	pub old_subtree_root: Hash,
	/// Merkle proof that `(receiver_para_id, old_subtree_root)` was a leaf in
	/// `old_provides_root`'s top-level tree.
	pub old_subtree_proof: MerkleSubtreeProof,

	/// The current provides root of the source (what's now in ProvidesRoots).
	pub new_provides_root: Hash,
	/// The subtree root under the new provides root.
	pub new_subtree_root: Hash,
	/// Merkle proof that `(receiver_para_id, new_subtree_root)` is a leaf in
	/// `new_provides_root`'s top-level tree.
	pub new_subtree_proof: MerkleSubtreeProof,

	/// If the source produced additional messages to this receiver since the
	/// block was built, this proof shows the old subtree is a valid prefix of
	/// the new subtree.
	pub subtree_extension: Option<MMRExtensionProof>,
}

/// Proves that an MMR root R_old is an ancestor of R_new, i.e. the MMR was
/// only appended to, not mutated.
#[derive(Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, Eq, Debug, TypeInfo)]
pub struct MMRExtensionProof {
	/// The peaks of the old MMR.
	pub old_peaks: Vec<Hash>,
	/// Number of leaves in the old MMR. Required to replay appends correctly.
	pub old_leaf_count: u64,
	/// The peaks of the new (larger) MMR.
	pub new_peaks: Vec<Hash>,
	/// Leaf hashes of messages appended between old and new state (in order).
	/// Replaying these appends starting from old_peaks must reproduce new_peaks.
	pub connecting_nodes: Vec<Hash>,
}

/// Per-source tracking for incoming speculative messages.
///
/// Only `last_processed` is required: subtree authentication flows through
/// `subtree_inclusion_proof` against the batch's `provides_root` (verified upstream
/// against the relay-chain `ProvidesRoots[source]`), and message authentication
/// flows through per-message MMR inclusion proofs against `batch.subtree_root`.
/// `last_processed` is the only piece of cross-block state required to enforce
/// continuity (`msg.position == last_processed + 1`) and prevent replay.
#[derive(Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, Eq, Debug, TypeInfo, Default)]
pub struct SourceState {
	/// Last processed message leaf index in the source's per-destination subtree.
	pub last_processed: u64,
}
