[package]
name = "snowbridge-inbound-queue-v2-runtime-api"
description = "Snowbridge Inbound Queue V2 Runtime API"
version = "0.2.0"
authors = ["Snowfork <contact@snowfork.com>"]
edition.workspace = true
repository.workspace = true
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api = { workspace = true }
snowbridge-merkle-tree = { workspace = true }
snowbridge-core = { workspace = true }
snowbridge-router-primitives = { workspace = true }
xcm = { workspace = true }

[features]
default = ["std"]
std = [
	"snowbridge-core/std",
	"snowbridge-merkle-tree/std",
	"snowbridge-router-primitives/std",
	"sp-api/std",
	"xcm/std",
]
