// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `cumulus_pallet_spec_messaging`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-10-07, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/penpal-runtime/penpal_runtime.wasm
// --pallet=cumulus_pallet_spec_messaging
// --header=cumulus/file_header.txt
// --output=cumulus/pallets/spec-messaging/src/weights.rs
// --wasm-execution=compiled
// --steps=50
// --repeat=20
// --heap-pages=4096
// --template=substrate/.maintain/frame-weight-template.hbs
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `cumulus_pallet_spec_messaging`.
pub trait WeightInfo {
	fn open_channel() -> Weight;
	fn accept_open_channel() -> Weight;
	fn close_channel() -> Weight;
	fn close_inbound_channel() -> Weight;
	fn suspend_inbound_channel() -> Weight;
	fn resume_inbound_channel() -> Weight;
	fn set_hrmp_closing() -> Weight;
	fn clear_hrmp_closing() -> Weight;
	fn enact_messages(c: u32, n: u32, b: u32, r: u32, ) -> Weight;
	fn send(b: u32, ) -> Weight;
	fn drain(h: u32, ) -> Weight;
	fn commit_streams_root(s: u32, h: u32, ) -> Weight;
}

/// Weights for `cumulus_pallet_spec_messaging` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SpecMessaging::OutChannels` (r:1 w:1)
	/// Proof: `SpecMessaging::OutChannels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundMessages` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutChannelsMeta` (r:1 w:1)
	/// Proof: `SpecMessaging::OutChannelsMeta` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::StreamCount` (r:1 w:1)
	/// Proof: `SpecMessaging::StreamCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::SendsThisBlock` (r:1 w:1)
	/// Proof: `SpecMessaging::SendsThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn open_channel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `36`
		//  Estimated: `3501`
		// Minimum execution time: 43_000_000 picoseconds.
		Weight::from_parts(45_000_000, 3501)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SpecMessaging::InChannels` (r:1 w:1)
	/// Proof: `SpecMessaging::InChannels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::InboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::InboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundMessages` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::StreamCount` (r:1 w:1)
	/// Proof: `SpecMessaging::StreamCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::SendsThisBlock` (r:1 w:1)
	/// Proof: `SpecMessaging::SendsThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn accept_open_channel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `36`
		//  Estimated: `3501`
		// Minimum execution time: 36_000_000 picoseconds.
		Weight::from_parts(38_000_000, 3501)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `SpecMessaging::OutChannels` (r:1 w:1)
	/// Proof: `SpecMessaging::OutChannels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutChannelsMeta` (r:1 w:1)
	/// Proof: `SpecMessaging::OutChannelsMeta` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundMessages` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::StreamCount` (r:1 w:1)
	/// Proof: `SpecMessaging::StreamCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::SendsThisBlock` (r:1 w:1)
	/// Proof: `SpecMessaging::SendsThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn close_channel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `72`
		//  Estimated: `3537`
		// Minimum execution time: 38_000_000 picoseconds.
		Weight::from_parts(40_000_000, 3537)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `SpecMessaging::InChannels` (r:1 w:1)
	/// Proof: `SpecMessaging::InChannels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SpecMessaging::InboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::InboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundMessages` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::SendsThisBlock` (r:1 w:1)
	/// Proof: `SpecMessaging::SendsThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn close_inbound_channel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `287`
		//  Estimated: `3752`
		// Minimum execution time: 41_000_000 picoseconds.
		Weight::from_parts(43_000_000, 3752)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `SpecMessaging::InChannels` (r:1 w:1)
	/// Proof: `SpecMessaging::InChannels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SpecMessaging::InboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::InboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundMessages` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::SendsThisBlock` (r:1 w:1)
	/// Proof: `SpecMessaging::SendsThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn suspend_inbound_channel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `287`
		//  Estimated: `3752`
		// Minimum execution time: 41_000_000 picoseconds.
		Weight::from_parts(43_000_000, 3752)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `SpecMessaging::InChannels` (r:1 w:1)
	/// Proof: `SpecMessaging::InChannels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SpecMessaging::InboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::InboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundMessages` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::SendsThisBlock` (r:1 w:1)
	/// Proof: `SpecMessaging::SendsThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn resume_inbound_channel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `349`
		//  Estimated: `3814`
		// Minimum execution time: 42_000_000 picoseconds.
		Weight::from_parts(44_000_000, 3814)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `SpecMessaging::OutChannels` (r:1 w:0)
	/// Proof: `SpecMessaging::OutChannels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::HrmpClosing` (r:0 w:1)
	/// Proof: `SpecMessaging::HrmpClosing` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_hrmp_closing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `72`
		//  Estimated: `3537`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 3537)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SpecMessaging::HrmpClosing` (r:0 w:1)
	/// Proof: `SpecMessaging::HrmpClosing` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn clear_hrmp_closing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SpecMessaging::InChannels` (r:64 w:64)
	/// Proof: `SpecMessaging::InChannels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::InboundFrontier` (r:64 w:64)
	/// Proof: `SpecMessaging::InboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MessageQueue::BookStateFor` (r:64 w:64)
	/// Proof: `MessageQueue::BookStateFor` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `MessageQueue::ServiceHead` (r:1 w:1)
	/// Proof: `MessageQueue::ServiceHead` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `SpecMessaging::ConsumptionOutbox` (r:1 w:1)
	/// Proof: `SpecMessaging::ConsumptionOutbox` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundFrontier` (r:64 w:0)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::SendsThisBlock` (r:1 w:1)
	/// Proof: `SpecMessaging::SendsThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundMessages` (r:64 w:64)
	/// Proof: `SpecMessaging::OutboundMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:64 w:64)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutChannels` (r:64 w:64)
	/// Proof: `SpecMessaging::OutChannels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutChannelsMeta` (r:64 w:64)
	/// Proof: `SpecMessaging::OutChannelsMeta` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MessageQueue::Pages` (r:0 w:65)
	/// Proof: `MessageQueue::Pages` (`max_values`: None, `max_size`: Some(105521), added: 107996, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 64]`.
	/// The range of component `n` is `[0, 1000]`.
	/// The range of component `b` is `[0, 102392]`.
	/// The range of component `r` is `[0, 64]`.
	fn enact_messages(c: u32, n: u32, b: u32, r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `203 + c * (99 ±0) + r * (48 ±0)`
		//  Estimated: `1666 + c * (2574 ±0) + r * (2524 ±0)`
		// Minimum execution time: 5_067_000_000 picoseconds.
		Weight::from_parts(5_359_000_000, 1666)
			// Standard Error: 886_859
			.saturating_add(Weight::from_parts(50_159_055, 0).saturating_mul(n.into()))
			// Standard Error: 8_665
			.saturating_add(Weight::from_parts(331_949, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().reads((6_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(r.into())))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(T::DbWeight::get().writes((6_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(r.into())))
			.saturating_add(Weight::from_parts(0, 2574).saturating_mul(c.into()))
			.saturating_add(Weight::from_parts(0, 2524).saturating_mul(r.into()))
	}
	/// Storage: `SpecMessaging::OutboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundMessages` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::StreamCount` (r:1 w:1)
	/// Proof: `SpecMessaging::StreamCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::SendsThisBlock` (r:1 w:1)
	/// Proof: `SpecMessaging::SendsThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[0, 102400]`.
	fn send(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `3469`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(25_443_275, 3469)
			// Standard Error: 0
			.saturating_add(Weight::from_parts(1_634, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `SpecMessaging::OutboundMessages` (r:64 w:64)
	/// Proof: `SpecMessaging::OutboundMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:65 w:64)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundFrontier` (r:64 w:64)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::StreamCount` (r:1 w:0)
	/// Proof: `SpecMessaging::StreamCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::BlockStreamsRoot` (r:0 w:1)
	/// Proof: `SpecMessaging::BlockStreamsRoot` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::SendsThisBlock` (r:0 w:1)
	/// Proof: `SpecMessaging::SendsThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::ConsumptionOutbox` (r:0 w:1)
	/// Proof: `SpecMessaging::ConsumptionOutbox` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `h` is `[0, 64]`.
	fn drain(h: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1628 + h * (126 ±0)`
		//  Estimated: `4969 + h * (2604 ±0)`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 4969)
			// Standard Error: 23_575
			.saturating_add(Weight::from_parts(34_128_370, 0).saturating_mul(h.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(h.into())))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(h.into())))
			.saturating_add(Weight::from_parts(0, 2604).saturating_mul(h.into()))
	}
	/// Storage: `SpecMessaging::BlockStreamsRoot` (r:1 w:1)
	/// Proof: `SpecMessaging::BlockStreamsRoot` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundFrontier` (r:193 w:0)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:65 w:0)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `s` is `[0, 128]`.
	/// The range of component `h` is `[0, 64]`.
	fn commit_streams_root(s: u32, h: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1688 + h * (111 ±0) + s * (51 ±0)`
		//  Estimated: `5143 + h * (2586 ±0) + s * (2527 ±0)`
		// Minimum execution time: 3_189_000_000 picoseconds.
		Weight::from_parts(49_835_445, 5143)
			// Standard Error: 241_366
			.saturating_add(Weight::from_parts(26_955_163, 0).saturating_mul(s.into()))
			// Standard Error: 480_443
			.saturating_add(Weight::from_parts(56_657_538, 0).saturating_mul(h.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(h.into())))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 2586).saturating_mul(h.into()))
			.saturating_add(Weight::from_parts(0, 2527).saturating_mul(s.into()))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SpecMessaging::OutChannels` (r:1 w:1)
	/// Proof: `SpecMessaging::OutChannels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundMessages` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutChannelsMeta` (r:1 w:1)
	/// Proof: `SpecMessaging::OutChannelsMeta` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::StreamCount` (r:1 w:1)
	/// Proof: `SpecMessaging::StreamCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::SendsThisBlock` (r:1 w:1)
	/// Proof: `SpecMessaging::SendsThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn open_channel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `36`
		//  Estimated: `3501`
		// Minimum execution time: 43_000_000 picoseconds.
		Weight::from_parts(45_000_000, 3501)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SpecMessaging::InChannels` (r:1 w:1)
	/// Proof: `SpecMessaging::InChannels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::InboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::InboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundMessages` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::StreamCount` (r:1 w:1)
	/// Proof: `SpecMessaging::StreamCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::SendsThisBlock` (r:1 w:1)
	/// Proof: `SpecMessaging::SendsThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn accept_open_channel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `36`
		//  Estimated: `3501`
		// Minimum execution time: 36_000_000 picoseconds.
		Weight::from_parts(38_000_000, 3501)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `SpecMessaging::OutChannels` (r:1 w:1)
	/// Proof: `SpecMessaging::OutChannels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutChannelsMeta` (r:1 w:1)
	/// Proof: `SpecMessaging::OutChannelsMeta` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundMessages` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::StreamCount` (r:1 w:1)
	/// Proof: `SpecMessaging::StreamCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::SendsThisBlock` (r:1 w:1)
	/// Proof: `SpecMessaging::SendsThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn close_channel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `72`
		//  Estimated: `3537`
		// Minimum execution time: 38_000_000 picoseconds.
		Weight::from_parts(40_000_000, 3537)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `SpecMessaging::InChannels` (r:1 w:1)
	/// Proof: `SpecMessaging::InChannels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SpecMessaging::InboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::InboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundMessages` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::SendsThisBlock` (r:1 w:1)
	/// Proof: `SpecMessaging::SendsThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn close_inbound_channel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `287`
		//  Estimated: `3752`
		// Minimum execution time: 41_000_000 picoseconds.
		Weight::from_parts(43_000_000, 3752)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `SpecMessaging::InChannels` (r:1 w:1)
	/// Proof: `SpecMessaging::InChannels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SpecMessaging::InboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::InboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundMessages` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::SendsThisBlock` (r:1 w:1)
	/// Proof: `SpecMessaging::SendsThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn suspend_inbound_channel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `287`
		//  Estimated: `3752`
		// Minimum execution time: 41_000_000 picoseconds.
		Weight::from_parts(43_000_000, 3752)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `SpecMessaging::InChannels` (r:1 w:1)
	/// Proof: `SpecMessaging::InChannels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SpecMessaging::InboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::InboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundMessages` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::SendsThisBlock` (r:1 w:1)
	/// Proof: `SpecMessaging::SendsThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn resume_inbound_channel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `349`
		//  Estimated: `3814`
		// Minimum execution time: 42_000_000 picoseconds.
		Weight::from_parts(44_000_000, 3814)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `SpecMessaging::OutChannels` (r:1 w:0)
	/// Proof: `SpecMessaging::OutChannels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::HrmpClosing` (r:0 w:1)
	/// Proof: `SpecMessaging::HrmpClosing` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_hrmp_closing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `72`
		//  Estimated: `3537`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 3537)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SpecMessaging::HrmpClosing` (r:0 w:1)
	/// Proof: `SpecMessaging::HrmpClosing` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn clear_hrmp_closing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SpecMessaging::InChannels` (r:64 w:64)
	/// Proof: `SpecMessaging::InChannels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::InboundFrontier` (r:64 w:64)
	/// Proof: `SpecMessaging::InboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MessageQueue::BookStateFor` (r:64 w:64)
	/// Proof: `MessageQueue::BookStateFor` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `MessageQueue::ServiceHead` (r:1 w:1)
	/// Proof: `MessageQueue::ServiceHead` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `SpecMessaging::ConsumptionOutbox` (r:1 w:1)
	/// Proof: `SpecMessaging::ConsumptionOutbox` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundFrontier` (r:64 w:0)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::SendsThisBlock` (r:1 w:1)
	/// Proof: `SpecMessaging::SendsThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundMessages` (r:64 w:64)
	/// Proof: `SpecMessaging::OutboundMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:64 w:64)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutChannels` (r:64 w:64)
	/// Proof: `SpecMessaging::OutChannels` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutChannelsMeta` (r:64 w:64)
	/// Proof: `SpecMessaging::OutChannelsMeta` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MessageQueue::Pages` (r:0 w:65)
	/// Proof: `MessageQueue::Pages` (`max_values`: None, `max_size`: Some(105521), added: 107996, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 64]`.
	/// The range of component `n` is `[0, 1000]`.
	/// The range of component `b` is `[0, 102392]`.
	/// The range of component `r` is `[0, 64]`.
	fn enact_messages(c: u32, n: u32, b: u32, r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `203 + c * (99 ±0) + r * (48 ±0)`
		//  Estimated: `1666 + c * (2574 ±0) + r * (2524 ±0)`
		// Minimum execution time: 5_067_000_000 picoseconds.
		Weight::from_parts(5_359_000_000, 1666)
			// Standard Error: 886_859
			.saturating_add(Weight::from_parts(50_159_055, 0).saturating_mul(n.into()))
			// Standard Error: 8_665
			.saturating_add(Weight::from_parts(331_949, 0).saturating_mul(b.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().reads((6_u64).saturating_mul(c.into())))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(r.into())))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
			.saturating_add(RocksDbWeight::get().writes((6_u64).saturating_mul(c.into())))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(r.into())))
			.saturating_add(Weight::from_parts(0, 2574).saturating_mul(c.into()))
			.saturating_add(Weight::from_parts(0, 2524).saturating_mul(r.into()))
	}
	/// Storage: `SpecMessaging::OutboundFrontier` (r:1 w:0)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundMessages` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::StreamCount` (r:1 w:1)
	/// Proof: `SpecMessaging::StreamCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::SendsThisBlock` (r:1 w:1)
	/// Proof: `SpecMessaging::SendsThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:1 w:1)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[0, 102400]`.
	fn send(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `3469`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(25_443_275, 3469)
			// Standard Error: 0
			.saturating_add(Weight::from_parts(1_634, 0).saturating_mul(b.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `SpecMessaging::OutboundMessages` (r:64 w:64)
	/// Proof: `SpecMessaging::OutboundMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:65 w:64)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundFrontier` (r:64 w:64)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::StreamCount` (r:1 w:0)
	/// Proof: `SpecMessaging::StreamCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::BlockStreamsRoot` (r:0 w:1)
	/// Proof: `SpecMessaging::BlockStreamsRoot` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::SendsThisBlock` (r:0 w:1)
	/// Proof: `SpecMessaging::SendsThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::ConsumptionOutbox` (r:0 w:1)
	/// Proof: `SpecMessaging::ConsumptionOutbox` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `h` is `[0, 64]`.
	fn drain(h: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1628 + h * (126 ±0)`
		//  Estimated: `4969 + h * (2604 ±0)`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 4969)
			// Standard Error: 23_575
			.saturating_add(Weight::from_parts(34_128_370, 0).saturating_mul(h.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().reads((3_u64).saturating_mul(h.into())))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(RocksDbWeight::get().writes((3_u64).saturating_mul(h.into())))
			.saturating_add(Weight::from_parts(0, 2604).saturating_mul(h.into()))
	}
	/// Storage: `SpecMessaging::BlockStreamsRoot` (r:1 w:1)
	/// Proof: `SpecMessaging::BlockStreamsRoot` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundFrontier` (r:193 w:0)
	/// Proof: `SpecMessaging::OutboundFrontier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SpecMessaging::OutboundLeafHashes` (r:65 w:0)
	/// Proof: `SpecMessaging::OutboundLeafHashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `s` is `[0, 128]`.
	/// The range of component `h` is `[0, 64]`.
	fn commit_streams_root(s: u32, h: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1688 + h * (111 ±0) + s * (51 ±0)`
		//  Estimated: `5143 + h * (2586 ±0) + s * (2527 ±0)`
		// Minimum execution time: 3_189_000_000 picoseconds.
		Weight::from_parts(49_835_445, 5143)
			// Standard Error: 241_366
			.saturating_add(Weight::from_parts(26_955_163, 0).saturating_mul(s.into()))
			// Standard Error: 480_443
			.saturating_add(Weight::from_parts(56_657_538, 0).saturating_mul(h.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(h.into())))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 2586).saturating_mul(h.into()))
			.saturating_add(Weight::from_parts(0, 2527).saturating_mul(s.into()))
	}
}
